#!/usr/bin/env node
/**
 * The standards-integrity ratchet: prove that no rule's protection has been weakened in silence.
 *
 * WHY THIS EXISTS. The standards-system spec requires a global invariant — that no human or AI
 * bypass, weaken, remove, reclassify, or reinterpret a standard because it blocks a desired
 * conclusion — and then asks the harder question: how can that invariant itself be protected and
 * tested? Prose cannot do it. A rule's strength lives in three fields, and all three are one edit
 * away from vanishing:
 *
 *   level          forbidden -> recommended, and a prohibition becomes a suggestion
 *   nonExemptible  true -> false, and the rule becomes waivable by writing a policy exception
 *   severity       error -> info, and the failure stops being reported as one
 *
 * Nothing in the catalog loader objects to any of those: each produces a perfectly valid rule. The
 * change is invisible precisely because the file that defines the rule is the file that was edited.
 *
 * WHAT THIS DOES. `artifacts/integrity-baseline.json` records those three fields for every rule, plus
 * the rule's existence. This script compares the live catalog against it. Weakening a rule therefore
 * requires editing the baseline too — which is a second, deliberate, reviewable act that shows up in
 * a diff on its own line and cannot be mistaken for a routine catalog edit. The ratchet does not make
 * weakening impossible; it makes weakening *visible*, which is what the invariant actually asks for.
 * A change that cannot be made accidentally and cannot be made quietly is a change someone chose.
 *
 * Strengthening is reported too, and passes. It is not a violation to make a rule stricter, but it is
 * still a change to the protection surface, and the report should say so rather than stay silent
 * about half of what it watches.
 *
 * LIKE THE SOURCE INVENTORY, THE BASELINE IS NEVER REGENERATED BY A RUN. A `--write` flag would
 * defeat the entire mechanism: the first response to a red build would be to run it. Update the file
 * by hand, and record the reason in CHANGELOG.md naming the rule id.
 *
 * Usage:
 *   node scripts/integrity.mjs           report, exit 1 on any drift
 *   node scripts/integrity.mjs --json    machine-readable
 */

import { readFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

import { loadCatalog, CatalogError } from "./catalog.mjs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BASELINE = path.join(ROOT, "artifacts/integrity-baseline.json");
const RULES_DIR = path.join(ROOT, "rules");
const JSON_OUT = process.argv.includes("--json");

/** The fields whose change alters how strongly a rule is enforced. */
const PROTECTED = ["level", "nonExemptible", "severity"];

/**
 * Ordered weakest-to-strongest so a change can be classified rather than merely detected. An
 * `optional` rule cannot fail a check at all; a `forbidden` one states a must-never.
 */
const LEVEL_STRENGTH = { optional: 0, recommended: 1, required: 2, forbidden: 3 };
const SEVERITY_STRENGTH = { info: 0, warning: 1, error: 2 };

function strengthOf(entry) {
  return {
    level: LEVEL_STRENGTH[entry.level] ?? -1,
    severity: SEVERITY_STRENGTH[entry.severity] ?? -1,
    nonExemptible: entry.nonExemptible ? 1 : 0,
  };
}

const drift = { weakened: [], strengthened: [], removed: [], added: [], malformed: [] };

// A half-present pair is drift, not a clean slate. Passing when either side is missing would mean the
// ratchet reports green during exactly the window in which it is not watching anything.
const haveBaseline = existsSync(BASELINE);
const haveRules = existsSync(RULES_DIR);

let catalog = null;
let baseline = null;

if (!haveBaseline && !haveRules) {
  // Genuinely nothing to protect yet: no catalog exists. This is the only clean no-op.
  report({ status: "no-catalog", note: "No rules/ directory and no baseline: nothing to protect yet." });
} else if (!haveBaseline) {
  drift.malformed.push(`rules/ exists but ${path.relative(ROOT, BASELINE)} does not`);
  report({ status: "drift" });
} else if (!haveRules) {
  drift.malformed.push(`${path.relative(ROOT, BASELINE)} exists but rules/ does not`);
  report({ status: "drift" });
} else {
  try {
    catalog = await loadCatalog(RULES_DIR);
  } catch (error) {
    if (!(error instanceof CatalogError)) throw error;
    // A catalog that will not load is a configuration fault, not a compliance verdict: exit 2.
    process.stderr.write(`integrity: the catalog does not load: ${error.message}\n`);
    process.exit(2);
  }
  baseline = JSON.parse(await readFile(BASELINE, "utf8"));
  const recorded = baseline.rules ?? {};

  for (const [id, entry] of Object.entries(recorded)) {
    const rule = catalog.rules.get(id);
    if (!rule) {
      drift.removed.push({ id, was: entry });
      continue;
    }
    for (const field of PROTECTED) {
      if (rule[field] === entry[field]) continue;
      const before = strengthOf(entry);
      const after = strengthOf(rule);
      const change = { id, field, from: entry[field], to: rule[field] };
      if (after[field] < before[field]) drift.weakened.push(change);
      else drift.strengthened.push(change);
    }
  }

  for (const id of catalog.rules.keys()) {
    if (!(id in recorded)) drift.added.push({ id });
  }

  report({ status: "compared" });
}

function report({ status, note }) {
  // A new rule is not a weakening, but an unrecorded rule is a hole in the ratchet: the next edit to
  // it would be invisible. So it fails, and the fix is one line in the baseline.
  const failures =
    drift.weakened.length + drift.removed.length + drift.added.length + drift.malformed.length;
  const ok = failures === 0;

  const result = {
    status,
    note,
    baseline: path.relative(ROOT, BASELINE).split(path.sep).join("/"),
    reviewedOn: baseline?.reviewedOn ?? null,
    rulesInCatalog: catalog ? catalog.rules.size : 0,
    rulesInBaseline: baseline ? Object.keys(baseline.rules ?? {}).length : 0,
    drift,
    ok,
  };

  if (JSON_OUT) {
    process.stdout.write(JSON.stringify(result, null, 2) + "\n");
    process.exit(ok ? 0 : 1);
  }

  const out = [];
  if (note) {
    out.push(note, "");
  } else {
    out.push(`Baseline:          ${result.baseline}`);
    out.push(`Reviewed on:       ${result.reviewedOn ?? "(not recorded)"}`);
    out.push(`Rules in catalog:  ${result.rulesInCatalog}`);
    out.push(`Rules in baseline: ${result.rulesInBaseline}`);
    out.push("");
  }

  for (const m of drift.malformed) out.push(`! ${m}`);
  for (const c of drift.weakened) {
    out.push(`! WEAKENED    ${c.id}: ${c.field} ${JSON.stringify(c.from)} -> ${JSON.stringify(c.to)}`);
  }
  for (const r of drift.removed) out.push(`! REMOVED     ${r.id}: in the baseline, not in the catalog`);
  for (const a of drift.added) out.push(`! UNRECORDED  ${a.id}: in the catalog, not in the baseline`);
  for (const c of drift.strengthened) {
    out.push(`  strengthened ${c.id}: ${c.field} ${JSON.stringify(c.from)} -> ${JSON.stringify(c.to)}`);
  }

  if (!ok) {
    out.push("");
    out.push("A rule's protection changed without the baseline changing with it. If the change is");
    out.push("intended, edit artifacts/integrity-baseline.json by hand and record the reason in");
    out.push("CHANGELOG.md naming the rule id. Never regenerate the baseline from a run: the whole");
    out.push("point is that weakening a rule cannot happen quietly (Standard 18).");
  } else if (!note) {
    out.push(
      drift.strengthened.length > 0
        ? "No rule was weakened. The strengthening above is recorded and permitted."
        : "Every rule's protection matches the reviewed baseline.",
    );
  }
  process.stdout.write(out.join("\n") + "\n");
  process.exit(ok ? 0 : 1);
}
